#!/usr/bin/env bash
# providers.sh — Providers configuration (PostgreSQL, Redis, pgAdmin, MinIO, Portainer)

provision_providers() {
  if [ "$SKIP_DOCKER" = false ]; then

    if [ "$SKIP_PGADMIN" = false ] && [ "$SKIP_POSTGRES" = true ]; then
      warn "pgAdmin requires PostgreSQL — skipping pgAdmin automatically"
      SKIP_PGADMIN=true
    fi

    ENABLED_PROVIDERS=""
    [ "$SKIP_POSTGRES"  = false ] && ENABLED_PROVIDERS="${ENABLED_PROVIDERS:+$ENABLED_PROVIDERS, }PostgreSQL"
    [ "$SKIP_REDIS"     = false ] && ENABLED_PROVIDERS="${ENABLED_PROVIDERS:+$ENABLED_PROVIDERS, }Redis"
    [ "$SKIP_PGADMIN"   = false ] && ENABLED_PROVIDERS="${ENABLED_PROVIDERS:+$ENABLED_PROVIDERS, }pgAdmin"
    [ "$SKIP_MINIO"     = false ] && ENABLED_PROVIDERS="${ENABLED_PROVIDERS:+$ENABLED_PROVIDERS, }MinIO"
    [ "$SKIP_PORTAINER" = false ] && ENABLED_PROVIDERS="${ENABLED_PROVIDERS:+$ENABLED_PROVIDERS, }Portainer"

    if [ -z "$ENABLED_PROVIDERS" ]; then
      warn "All providers skipped — no compose file generated"
    else
      step "Configuring Providers ($ENABLED_PROVIDERS)"

      local PROVIDERS_DIR="$HOME/providers"
      mkdir -p "$PROVIDERS_DIR/providers/postgres/init"
      mkdir -p "$PROVIDERS_DIR/providers/redis"
      mkdir -p "$PROVIDERS_DIR/providers/pgadmin"

      _providers_write_compose "$PROVIDERS_DIR"
      _providers_write_configs "$PROVIDERS_DIR"
      _providers_write_systemd "$PROVIDERS_DIR"

      success "Providers configured at: $PROVIDERS_DIR ($ENABLED_PROVIDERS)"
      [ "$SKIP_PGADMIN"   = false ] && info "pgAdmin   -> http://localhost:5050  (admin@admin.com / admin)"
      [ "$SKIP_MINIO"     = false ] && info "MinIO     -> http://localhost:9001  (minioadmin / minioadmin)"
      [ "$SKIP_PORTAINER" = false ] && info "Portainer -> http://localhost:8001"
    fi
  fi
}

_providers_write_compose() {
  local PROVIDERS_DIR="$1"

  cat > "$PROVIDERS_DIR/docker-compose.yml" << 'COMPOSE_HEADER'
# =============================================================================
# docker-compose.yml - Providers (Shared Services)
# Generated by setup-wsl.sh — re-run with different flags to change services.
# Usage: docker compose up -d
# =============================================================================

services:
COMPOSE_HEADER

  if [ "$SKIP_POSTGRES" = false ]; then
    cat >> "$PROVIDERS_DIR/docker-compose.yml" << 'POSTGRES_SVC'

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: ${TZ:-America/Sao_Paulo}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./providers/postgres/init:/docker-entrypoint-initdb.d
    command: >
      postgres
        -c shared_buffers=512MB
        -c max_connections=100
        -c work_mem=32MB
        -c maintenance_work_mem=256MB
        -c effective_cache_size=1536MB
        -c wal_buffers=16MB
        -c synchronous_commit=off
        -c checkpoint_completion_target=0.9
        -c random_page_cost=1.1
        -c effective_io_concurrency=200
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
POSTGRES_SVC
  fi

  if [ "$SKIP_REDIS" = false ]; then
    cat >> "$PROVIDERS_DIR/docker-compose.yml" << 'REDIS_SVC'

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - ./providers/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
REDIS_SVC
  fi

  if [ "$SKIP_PGADMIN" = false ]; then
    cat >> "$PROVIDERS_DIR/docker-compose.yml" << 'PGADMIN_SVC'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      TZ: ${TZ:-America/Sao_Paulo}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./providers/pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared-network
PGADMIN_SVC
  fi

  if [ "$SKIP_MINIO" = false ]; then
    cat >> "$PROVIDERS_DIR/docker-compose.yml" << 'MINIO_SVC'

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      TZ: ${TZ:-America/Sao_Paulo}
    ports:
      - "${MINIO_PORT_API:-9000}:9000"
      - "${MINIO_PORT_CONSOLE:-9001}:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
MINIO_SVC
  fi

  if [ "$SKIP_PORTAINER" = false ]; then
    cat >> "$PROVIDERS_DIR/docker-compose.yml" << 'PORTAINER_SVC'

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "${PORTAINER_HTTP_PORT:-8001}:9000"
      - "${PORTAINER_HTTPS_PORT:-8443}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - shared-network
PORTAINER_SVC
  fi

  cat >> "$PROVIDERS_DIR/docker-compose.yml" << 'COMPOSE_FOOTER'

networks:
  shared-network:
    name: shared-network
    driver: bridge

volumes:
COMPOSE_FOOTER

  [ "$SKIP_POSTGRES"  = false ] && echo "  postgres_data:"  >> "$PROVIDERS_DIR/docker-compose.yml"
  [ "$SKIP_REDIS"     = false ] && echo "  redis_data:"     >> "$PROVIDERS_DIR/docker-compose.yml"
  [ "$SKIP_PGADMIN"   = false ] && echo "  pgadmin_data:"   >> "$PROVIDERS_DIR/docker-compose.yml"
  [ "$SKIP_MINIO"     = false ] && echo "  minio_data:"     >> "$PROVIDERS_DIR/docker-compose.yml"
  [ "$SKIP_PORTAINER" = false ] && echo "  portainer_data:" >> "$PROVIDERS_DIR/docker-compose.yml"
}

_providers_write_configs() {
  local PROVIDERS_DIR="$1"

  if [ ! -f "$PROVIDERS_DIR/.env" ]; then
    cat > "$PROVIDERS_DIR/.env" << 'ENV_EOF'
# =============================================================================
# .env - Providers (Shared Services)
# =============================================================================

# PostgreSQL
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=postgres
POSTGRES_PORT=5433

# Redis
REDIS_PORT=6379

# pgAdmin - http://localhost:5050
PGADMIN_EMAIL=admin@admin.com
PGADMIN_PASSWORD=admin
PGADMIN_PORT=5050

# MinIO - S3 API and Console
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
MINIO_PORT_API=9000
MINIO_PORT_CONSOLE=9001

# Portainer - http://localhost:8001
PORTAINER_HTTP_PORT=8001
PORTAINER_HTTPS_PORT=8443

# Timezone
TZ=America/Sao_Paulo
ENV_EOF
    warn ".env file created with default values - edit passwords at: $PROVIDERS_DIR/.env"
  else
    warn ".env already exists at $PROVIDERS_DIR/.env - kept unchanged"
  fi

  if [ "$SKIP_REDIS" = false ]; then
    cat > "$PROVIDERS_DIR/providers/redis/redis.conf" << 'REDIS_EOF'
# ==============================================
# Redis - Configuration
# ==============================================

bind 0.0.0.0
port 6379
protected-mode no

# Persistence
appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru

# Logging
loglevel notice

# Timeout
timeout 0
tcp-keepalive 300

# Databases
databases 16
REDIS_EOF
  fi

  if [ "$SKIP_POSTGRES" = false ]; then
    cat > "$PROVIDERS_DIR/providers/postgres/init/01-init-db.sql" << 'SQL_EOF'
-- =============================================================================
-- 01-init-db.sql - PostgreSQL initialization
-- =============================================================================

-- Useful extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

DO $$
BEGIN
  RAISE NOTICE 'PostgreSQL initialized successfully!';
END $$;
SQL_EOF
  fi

  if [ "$SKIP_PGADMIN" = false ]; then
    cat > "$PROVIDERS_DIR/providers/pgadmin/servers.json" << 'JSON_EOF'
{
    "Servers": {
        "1": {
            "Name": "PostgreSQL Local",
            "Group": "Servers",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "SSLMode": "prefer"
        }
    }
}
JSON_EOF
  fi
}

_providers_write_systemd() {
  local PROVIDERS_DIR="$1"
  local PROVIDERS_SERVICE="/etc/systemd/system/providers.service"

  sudo tee "$PROVIDERS_SERVICE" > /dev/null << EOF
[Unit]
Description=Dev Providers ($ENABLED_PROVIDERS)
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$PROVIDERS_DIR
ExecStartPre=/bin/bash -c 'i=0; until docker info >/dev/null 2>&1; do i=\$((i+1)); [ \$i -ge 30 ] && exit 1; sleep 2; done'
ExecStartPre=-/usr/bin/docker container prune -f
ExecStart=/usr/bin/docker compose up -d --remove-orphans --force-recreate
ExecStop=/usr/bin/docker compose down --remove-orphans
ExecStopPost=-/usr/bin/docker container prune -f
TimeoutStartSec=180
User=$USER

[Install]
WantedBy=multi-user.target
EOF

  sudo systemctl daemon-reload
  if ! systemctl is-enabled providers.service &>/dev/null; then
    sudo systemctl enable providers.service
    success "Providers service enabled - starts automatically with WSL"
  else
    success "Providers service updated"
  fi
}
