# ==============================================
# Redis — Configuração
# ==============================================

# Rede
bind 0.0.0.0
port 6379
protected-mode no

# Persistência (AOF + RDB snapshots)
appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000

# Memória
maxmemory 256mb
maxmemory-policy allkeys-lru

# Logs
loglevel notice

# Timeout
timeout 0
tcp-keepalive 300

# Databases
databases 16
